### ISSUE TITLE
The page build failed with the tag "asset_path"

### ISSUE THREAD

**Issue by nowStackOverflow** [nielsenramon/chalk#1]
The page build failed with the following error:

The tag `asset_path` on line 1 in `_posts/2016-10-15-chalk-sample-post-with-all-elements.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

I think, The tag "og_image" is not configured....

**Comment by nielsenramon** [comment]
@nowStackOverflow I'll fix that tonight! Thanks for finding out :)

**Comment by nielsenramon** [comment]
@nowStackOverflow I cannot replicate this issue. For me it works perfectly.

<img width="1709" alt="screen shot 2016-11-03 at 21 09 15" src="https://cloud.githubusercontent.com/assets/1246672/19983306/ce424606-a209-11e6-9e57-f52cbf697a9b.png">

Did you run bundle install?

**Comment by longxyer** [comment]
@nielsenramon Hei~I also have the same error.
I just forked your theme and changed the CNAME. And every time I tried to change some original documents or create a new one, I got a e-mail to remind me there is en error.

**Comment by nowStackOverflow** [comment]
I tried many ways to solve this error.  but I haven't figured out yet. This repository is being used experimentally on my [repository](https://github.com/nowij/nowij.github.io).

**Comment by nielsenramon** [comment]
@nowStackOverflow @longxyer You cannot use Chalk the default way on Jekyll btw, you have to use `bin/deploy` to do so. Chalk uses non-supported plugins.

`bin/deploy` will push a working version to gh-pages branch :)

**Comment by nowStackOverflow** [comment]
Thank you for your answers...
So...
Do I have to repeat it everytime?
like this?

```
git add -fA
git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
git push -f -q origin gh-pages
```

**Comment by nielsenramon** [comment]
@nowStackOverflow Please read the README.

All you have to do is push to your master branch (or any other branch) and run `bin/deploy`
This will take care of everything.

More information can be found here: http://kickster.nielsenramon.com/
