### ISSUE TITLE
Problems Deploying

### ISSUE THREAD

**Issue by rollonbears234** [nielsenramon/chalk#10]
Thanks in advanced for your help, have spent hours trying to get this to work and am only making an issue when I don't think I can do it myself. 

#### My steps

So I took the template, added my empty username.github.io repo, and ran `bin/setup`. This runs successfully with no errors. 

I then run `bundle exec jekyll serve` and I went to `http://127.0.0.1:4000/`. This works successfully. 

Finally I run bin/deploy. This works and I get the following 

> Switched to branch 'master'
    Deployed Successfully!

I then realized I have no master branch and on my page settings it said I need a master too. 

I read that for personal pages, we can only use the master branch and not the gh-pages link. So I ran `git merge master gh-pages`. 

This worked! Which is great, but, now how do I make changes... 

#### The issue

After the following steps I have a working website at rollonbears234.github.io, but now I cannot make any changes because the bin/setup and all the other important files seem to be missing. 

I could start from scratch, but I am not sure this is a good strategy going forward because it would be tedious to make any change if I ever want to add a post or something like that.

**Comment by nielsenramon** [comment]
@rollonbears234 You need 2 branches. Master and gh-pages. Master is the Jekyll project and gh-pages is the one the deploy script uses so don't use that one youself. If you run on bin/deploy on your master branch everything should work perfectly.

You can never merge the gh-pages branch in your working branch as that only contains the generated static website :)

**Comment by krishpop** [comment]
Hi @nielsenramon. I'm not sure if this is a recent change, but as of now, it seems that Github does not allow deploying site from the gh-pages pages branch for users and orgs, and has only allowed the gh-pages option to remain for project pages. Do you know of a way around this?

For reference:
https://help.github.com/articles/user-organization-and-project-pages/

**Comment by nielsenramon** [comment]
@krishpop Don't name your repo xxx.github.io ;-)
