### ISSUE TITLE
Scroll appear doesn't degrade nicely without js

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#101]
Page is all blank and elements don't appear since the js doesn't run, meaning that  the class of such elements isn't modified.

To fix it, one needs to add the css to the plugin itself. `</noscript>` tags are no good as some popular blockers like uMatrix don't process them as they use CSP.

I'll submit a PR as soon as I get a chance.

**Comment by nielsenramon** [comment]
@migueldemoura This appear on scroll thing is killing me haha. Looking forward to your PR :-p
