### ISSUE TITLE
Deploy success. But no display page.

### ISSUE THREAD

**Issue by koansang** [nielsenramon/chalk#105]
I'm run `./bin/deploy` and deployed successfully.
But page error when enter the my Github pages.

Error message is :
![image](https://user-images.githubusercontent.com/12390185/29919660-2418d28a-8e85-11e7-8991-76cd5c5d5863.png)

![image](https://user-images.githubusercontent.com/12390185/29920720-b1ae510c-8e89-11e7-8c2c-d61295169b81.png)

What's problem?

**Comment by koansang** [comment]
I think beacause don't set base url.
How do I set the base url?

**Comment by koansang** [comment]
I fixed this issue.

**Comment by migueldemoura** [comment]
So you just changed https://github.com/nielsenramon/chalk/blob/master/bin/deploy#L19 to account for a custom baseurl? This may be useful for others.

**Comment by koansang** [comment]
@migueldemoura yes~!!
For example,  If run `bundle exec jekyll build --baseurl dev` will make default static url is `https://xxxx.github.io/dev`

**Comment by migueldemoura** [comment]
Did you add the baseurl config to `_config.yml`?

**Comment by koansang** [comment]
@migueldemoura 
No. How get `_config.yml` option in `deploy` file?

**Comment by migueldemoura** [comment]
Add a line with: `baseurl: dev`, to `_config.yml`.

Source: https://jekyllrb.com/docs/configuration/

**Comment by koansang** [comment]
@migueldemoura 
Thanks a lot~!!

**Comment by migueldemoura** [comment]
Glad that helped!

**Comment by nielsenramon** [comment]
@migueldemoura Thanks for the help! :-) You think we should add something to the readme for this?

**Comment by migueldemoura** [comment]
@nielsenramon, might be a good idea, seems like a common enough desire among users
