### ISSUE TITLE
Update http://jekyllthemes.org/themes/chalk/ to match README

### ISSUE THREAD

**Issue by alzeih** [nielsenramon/chalk#106]
http://jekyllthemes.org/themes/chalk/ doesn't match information provided in the README here.

e.g: it refers to Bower, which has been replaced by Yarn.

https://github.com/mattvh/jekyllthemes/blob/master/_posts/2016-10-31-chalk.markdown

**Comment by migueldemoura** [comment]
Shouldn't this be posted to @mattvh's repository?

**Comment by alzeih** [comment]
The post was created by @nielsenramon (https://github.com/mattvh/jekyllthemes/pull/399) and relates to this project so I think this issue belongs here, but if you think opening an issue on https://github.com/mattvh/jekyllthemes would be more effective please go ahead. A pull request would definitely belong on @mattvh's repository.
