### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by sidv1993** [nielsenramon/chalk#108]
I followed the exact steps mentioned in the README

- Set up everything
- Added a 'dev' branch (not master)
- Ran bin/deploy successfully

But I still see the following message in the settings tab

Your site is having problems building: The tag asset_path on line 1 in _includes/image.html, is not a recognized Liquid tag.

Pls help!

**Comment by migueldemoura** [comment]
Can you re-run `bin/setup`?

**Comment by sidv1993** [comment]
I ran bin/setup and bin/deploy again. I didn't get any errors while doing so, but I still get 404 Page Not Found when I load my page and the same error message in the settings tab. Since mine is a user page, it is directly being sourced from the master branch. Could that be the reason? I am new to Jekyll so any help would be appreciated!

**Comment by migueldemoura** [comment]
I use another service to host the static files, so I'm not the best person to help you out with this one. @nielsenramon, is more knowledgeable than me on this pattern.

However, on the the README.md there's this paragraph (emphasis mine):

> Important note: Chalk does not support the standard way of Jekyll hosting on GitHub Pages. You need to deploy your working branch (can be any branch, **for xxx.github.io users: use another branch than master**) with the bin/deploy script. This is because Chalk uses Jekyll plugins that aren't supported by GitHub pages. The bin/deploy script will automatically build the entire project, then push it to the gh-pages branch of your repo. The script creates that branch for you so no need to create it yourself.

Are you using xxx.github.io? Can you try using another branch with `bin/deploy`?

**Comment by sidv1993** [comment]
I am using xxx.github.io. But I have created a new branch (dev) that is separate from my master branch, and am running all the commands in dev. Am I missing something here?

**Comment by nielsenramon** [comment]
@sidv1993 Can you remove the `master` branch eventually and see if that helps? You could also switch the target branch in the repo settings!

Let me know if that helps.

**Comment by sidv1993** [comment]
@nielsenramon I tried that. Didn't work. What do you mean by switching the target branch? I have set my default branch to (dev) and not master.

**Comment by nielsenramon** [comment]
@sidv1993 Can you set it to the `gh-pages` branch and see if that worked (in the settings)?

**Comment by migueldemoura** [comment]
@sidv1993, long shot, but did you change the base url?

**Comment by sidv1993** [comment]
@nielsenramon I tried that but it didn't work. Infact, when I removed my master branch the settings page indicated that "Github pages isn't set up". So it seems that I need to keep my master branch in there. And the error that I get when doing so is " Your site is having problems building: The tag asset_path on line 1 in _includes/image.html, is not a recognized Liquid tag"

@migueldemoura  I had added a baseurl:xxx.github.io in my _config.yml, but I have removed it. I just have url: http://127.0.0.1:4000 currently.

It seems to me that the master branch is having an issue with the {% asset_path } liquid tag. Is there a way add it correctly?

**Comment by migueldemoura** [comment]
@sidv1993, the baseurl option is to change your blog home from` xxx.github.io/` to `xxx.github.io/$baseurl`, and requires an ajustment to the deploy script. Since you removed that option and its "_invalid_" value, could you try and redo the deploy? There's a similar issue here https://github.com/nielsenramon/chalk/issues/108. This may be the reason for the "404", with the other error coming as a result of the branch modifications.

**Comment by sidv1993** [comment]
I tried removing baseurl, commiting & pushing the change, running bin/deploy from my (dev) branch. But didn't work. Here is a screenshot of the issue.
<img width="773" alt="screen shot 2017-10-15 at 11 11 14 am" src="https://user-images.githubusercontent.com/17081489/31586679-c2186a7c-b199-11e7-922e-7da5aeff7fdc.png">
It seems to me that the master branch is required for hosting username.github.pages. But while doing bin/deploy, it is advised to use a branch other than master for xxx.github.io.

**Comment by sidv1993** [comment]
Do I have to do something similar with `bower install --allow-root` as mentioned in [https://github.com/nielsenramon/chalk/issues/18](url)

**Comment by sidv1993** [comment]
Fixed! I was able to get it to work using @cheny1ran comments in #18 about merging `gh-pages` and the `master branch`. Here is what I did-
- Ran `bin/deploy` on (dev) branch, which created a new `gh-pages` branch
- `git checkout master` and `git merge gh-pages`
- Started up `xxx.github.io` and it showed up.
Thanks, @migueldemoura  and @nielsenramon  for the help!

**Comment by nielsenramon** [comment]
@sidv1993 Glad you got it working! I really need to come up with a better way of supporting .github.io sites 😃
