### ISSUE TITLE
SVGs don't render without svgxuse.js

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#113]
Fix: on each `svg > use` declaration, add `xmlns="http://www.w3.org/2000/svg"` to the svg. The svgs could also be abstracted to a include.html.

**Comment by madcatsu** [comment]
Interesting, svgxuse.js is obviously a polyfill for browsers that don't support the `use` declaration. Is this issue trying to cater to users who disable JavaScript in their browser?

**Comment by migueldemoura** [comment]
Correct. Adding that line on each svg fixes it.

**Comment by nielsenramon** [comment]
@migueldemoura Added on each svg > use declaration that line, thanks ;-)
