### ISSUE TITLE
Serving from subdirectory (e.g. /blog)

### ISSUE THREAD

**Issue by martomi** [nielsenramon/chalk#118]
I'm trying to run the template under domain of the format www.domain.com/blog

I've configured the url in `_config.yml` appropriately but the template uses relative paths on many places and those point to the root of the domain.

Is there an easy way to fix this (any configuration that I'm missing?) or do I have to change relative paths to absolute paths everywhere?

**Comment by migueldemoura** [comment]
Could you provide some examples of those paths? Thanks!

**Comment by martomi** [comment]
All assets for example. The CSS doesn't load because it's linked the following way:

```<link rel="stylesheet" href="/assets/light.css">```

The `/` in front makes it look for the assets folder in the root of the domain. Actually just removing that slash in front should fix the problem. Where do you generate the assets paths? I could take a look and try to fix it.

**Comment by migueldemoura** [comment]
Have you added `baseurl` in `_config.yml`?

If you have, this could be an issue with `jekyll-assets` not taking into account such parameter. Do you have a repo online to reproduce this?

**Comment by martomi** [comment]
Adding `baseurl` worked for the assets. However posts link still don't work. Now they include the baseurl with a `/` in front which breaks it. Here's an example post link:

```/https://domain.com/blog/posts/introducing-chalk```

Also after this works I would suggest adding the `baseurl` to the _config.yml as well. Maybe it is apparent for users experienced with Jekyll. However I was totally unaware of the existence of this parameter and its difference to the `url` parameter.

Thanks for the quick responses!

**Comment by martomi** [comment]
Oops my bad. I added the whole url to `baseurl` while I was supposed to only add `/blog` there. I think that fixes it! 

Thanks for the help!!

**Comment by migueldemoura** [comment]
Glad that helped! :smile:

I agree, some users have had the exact same issue.
Feel free to submit a PR adding that parameter and a small comment!
