### ISSUE TITLE
JavaScript not reloading properly on redirects

### ISSUE THREAD

**Issue by TheGrandmother** [nielsenramon/chalk#120]
I am having a problem.

I'm trying to use MathJax (which is awesome) in some of my posts.

It works if i go directly to the URL of the post. But if I go to the post from the contents table on the main page Mathjax does not load and i have to do a manual refresh to get it to load.

I have created a file called `_includes/mathjax_support` like this:
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    TeX: {
      equationNumbers: {
        autoNumber: "AMS"
      }
    },
    tex2jax: {
      inlineMath: [ ['$','$'], ['\(', '\)'] ],
      displayMath: [ ['$$','$$'] ],
      processEscapes: true,
    }
  });
</script>
<script type="text/javascript"
        src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

And i have modified the `posts.html` file with:
```
<!doctype html>
<html lang="en">
<head>
  {% if page.use_math %}
    {% include mathjax-support %}
  {% endif %}
</head>
{% include head.html %}
{% include javascripts.html %}
<body>
  <main>
    <div class="grid grid-centered">
      <div class="grid-cell">
        {% include navigation.html %}
...
...
...
```

And I have added have added a `use_math: true` directive to the specific post.

I haven't been able to find any information after some googling and maybe its something with how jekyll does the navigation?

**Comment by migueldemoura** [comment]
Jekyll generates static files, so I'd suggest disabling all JS from chalk and try again. Let me know how it goes :)

**Comment by TheGrandmother** [comment]
Yhea I know that Jekyll generates static files and that is a large part of my confusion :p 

Removing the lines:
```
{% javascript vendor %}
{% javascript application %}
```
 of `_includes/javascripts.html`

Solves the problem.

And now I'm suspecting more owls in the swapms. I had another problem with reveal not working after redirects also so i disabled them everywhere. And as i look into `_assets/aplication.js` file it seems like that one might also not get loaded properly and that caused the reveal to be broken.

Uncommenting the lines in `_assets/vendor.js` seems to have solved the problem.
Will test and see if it solves the reveal problem.

**Comment by TheGrandmother** [comment]
Sorry, I was being an idiot as usual ^-^

I had tried to migrate some stuff from an older broken chalk blog i had and had accidentaly overwritten some stuff.
Now everything is working as it is supposed to do :3

**Comment by migueldemoura** [comment]
So everything works with the latest chalk version? Glad everything worked out! :D

**Comment by TheGrandmother** [comment]
Yupp, it's working great now :) Even the font color in the equations seems to be correct which is pretty neat!
