### ISSUE TITLE
Revert #119

### ISSUE THREAD

**Issue by nielsenramon** [nielsenramon/chalk#121]
Revert the change here: https://github.com/nielsenramon/chalk/pull/119

**Comment by migueldemoura** [comment]
To paraphrase what was said on that PR, we should probably upgrade to jekyll-assets v3, the breaking changes are trivial to fix and are contained here: https://github.com/migueldemoura/migueldemoura.com/commit/6c498dbbe53a2f17db3d34848a6a3716261953cc

**Comment by nielsenramon** [comment]
@migueldemoura Absolutely, I got some spare time in the coming days, I'll try my best to check off some of the issues.

**Comment by migueldemoura** [comment]
One could keep the baseurl key empty, along with a comment, as that might help out new users.
