### ISSUE TITLE
Liquid Exception: Liquid syntax error (chalk/_includes/image.html line 1): Unknown tag 'asset_path'

### ISSUE THREAD

**Issue by leonardo-hammer** [nielsenramon/chalk#123]
I have done `bin/setup`, all bundle are installed.

This error occur after `bundle exec jekyll serve`.

Here is the full log:

```shell
~/g/chalk (master|✔) $ bundle exec jekyll serve
Configuration file: /Users/leonardo/git/chalk/_config.yml
            Source: /Users/leonardo/git/chalk
       Destination: /Users/leonardo/git/chalk/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
           Assets:  Compression is ignored w/ SourceMaps
  Liquid Exception: Liquid syntax error (/Users/leonardo/git/chalk/_includes/image.html line 1): Unknown tag 'asset_path' included in /Users/leonardo/git/chalk/_posts/2016-10-15-chalk-sample-post-with-all-elements.md
jekyll 3.6.2 | Error:  Liquid syntax error (/Users/leonardo/git/chalk/_includes/image.html line 1): Unknown tag 'asset_path' included 
```

**Comment by ivangabriele** [comment]
I think this comes from the new major version of [https://github.com/envygeeks/jekyll-assets](https://github.com/envygeeks/jekyll-assets) that handles assets differently. I'm just a very beginner in Ruby but I was able to fix it by changing this line in **Gemfile** :

    gem "jekyll-assets"

by :

    gem "jekyll-assets", "~> 2.4"

in order to use .

you just have to re-do a `bundle install` afterwards and it works 😉.

**Comment by migueldemoura** [comment]
@ivangabriele is correct, the version should be pinned. Feel free to send a PR with that.

Related: #119 (jekyll-assets upgrade).

**Comment by leonardo-hammer** [comment]
@ivangabriele It's worked! Thanks for help.

**Comment by nielsenramon** [comment]
@leonardo-hammer @ivangabriele @migueldemoura If you now pull master you won't need to add the fix anymore! Everything is updated to Jekyll Assets 3
