### ISSUE TITLE
Refactor Use of 'asset_path' to 'asset'

### ISSUE THREAD

**Issue by wyntre** [nielsenramon/chalk#138]
'asset_path' is no longer supported in Jekyll.

https://github.com/envygeeks/jekyll-assets/issues/429

**Comment by wyntre** [comment]
so it looks like they need to have @path added as well so the links don't break.

**Comment by nielsenramon** [comment]
@wyntre I don't think we use asset_path anymore. Are you using the last version of Chalk?

**Comment by wyntre** [comment]
@nielsenramon you're right.  i thought i had pulled down the updated version, but my development server was having issues.  I rebuilt from scratch this morning and everything is good.
