### ISSUE TITLE
Can't RSS subscribe to whole page content

### ISSUE THREAD

**Issue by arikalfus** [nielsenramon/chalk#141]
I would like to cross-post articles on my site using the Chalk theme as well as popular blog platforms. This is supported by RSS subscriptions that contain the entire article content in `<content:encoded>stuff</content:encoded>` sections per `<item>`.

Given the Jinja templating, I imagine that `{{ content }}` variable in `_layouts/post.html`  is what we want in the `content:encoded` sections, but I haven't been able to isolate that value for each post yet. Am I being dumb, or is this not supported given the templating setup right now? Can we get it supported?

**Comment by arikalfus** [comment]
I've currently tried `<content:encoded>{{ page.content | xml_escape }}</content:encoded>` and the same without `xml_escape`. Both break the RSS feed.

**Comment by nielsenramon** [comment]
@arikalfus What is the error you are getting? Code looks indeed fine.

**Comment by arikalfus** [comment]
I added the `content` line to `rss.xml`:
![image](https://user-images.githubusercontent.com/6969296/36766478-1055fbda-1c04-11e8-90b7-6f277e25b9b6.png)

And get this RSS page:
![image](https://user-images.githubusercontent.com/6969296/36766486-1b80ebbe-1c04-11e8-979c-543eebcc283d.png)

The syntax works so the RSS page loads and displays the post title and description, but I don't get any of the actual content.

**Comment by nielsenramon** [comment]
@arikalfus I'm not sure that content type is supported? I would change the description to the content one if you'd like.

**Comment by arikalfus** [comment]
I've tried removing the `type` attribute from `content`. This is definitely a Jekyll syntax thing and not specific to Chalk, but it would be nice if this could be included. We should be able to have the excerpt in the `description` and the full content in `content`...

Alternatively, I can give up and just have the `description` be the full article content. @nielsenramon, this can be configured with a `_config.yml` option, set to the original `post.description` by default. But if the config option is enabled, can set the full article content instead. What do you think?

**Comment by arikalfus** [comment]
Yeah, the `content` field is not supported in RSS 2.0. I was basing that on Medium's RSS feeds, which do use that field. Let me know if you'd like me to submit a PR with the Jinja logic for the `description` described above

**Comment by nielsenramon** [comment]
@arikalfus No need, I think we'll keep the description in there for now. I feel it's more common. Thanks for the insights!
