### ISSUE TITLE
Replace Fluidbox with Zooming

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#148]
[Zooming](https://github.com/kingdido999/zooming) doesn't require jQuery and has neat baked-in features like close on scroll and on ESC. I also found it to be more responsive on mobile.

For a complete drop-in replacement, we would need this merged: https://github.com/kingdido999/zooming/pull/61

Demo of how it looks: https://migueldemoura.com/posts/edp-vulnerability-disclosure/ (click the images).

**Comment by nielsenramon** [comment]
@migueldemoura I like it!
