### ISSUE TITLE
Title becomes bold during navigation

### ISSUE THREAD

**Issue by avarabyeu** [nielsenramon/chalk#15]
Sometimes title becomes bold, then becomes normal again. 
Steps to reproduce:
1. Open http://chalk.nielsenramon.com/
2. Click at 'How to configure Chalk' (it usually appears with this blog post)

Looking forward for a fix.
P.S. Theme is awesome, many thanks for sharing it!

**Comment by nielsenramon** [comment]
@avarabyeu That's normal, it's the google fonts async delay. So it uses the system font first until the google font has been downloaded. I know it's not that nice but it's the optimal option for Google PageSpeed. You can disable the async version if you just include the default script tag from their website!

**Comment by avarabyeu** [comment]
@nielsenramon just replaced 'WebFont.load...' with standard <link href...> directives, but still no luck, behaviour is the same.  Maybe, i'm doing smth wrong. May i ask you to have a look? 
```html
{% javascript vendor %}
{% javascript application %}

<!-- <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script> -->
<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:700;subset=cyrillic" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700;subset=cyrillic" rel="stylesheet">

<!-- <script>
  WebFont.load({
    google: {
      families: ['Cormorant Garamond:700', 'Lato:300,400,700']
    }
  });
</script> -->

{% if site.ga_analytics %}
  <script>
    window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
    ga('create','{{ site.ga_analytics }}','auto');ga('send','pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>
{% endif %}
```

**Comment by nielsenramon** [comment]
@avarabyeu Put the 2 scripts in the `<head>` ;-)
Also you can make 1 script link of that.

**Comment by avarabyeu** [comment]
@nielsenramon Thanks a lot!! 👍
