### ISSUE TITLE
Github pages no longer building properly

### ISSUE THREAD

**Issue by nbulischeck** [nielsenramon/chalk#154]
I mirrored my old website repo (https://github.com/nbulischeck/website) to a new repo (https://nbulischeck.github.io/project6/) and rebuilt the project. I'm now getting 404 errors when github tries to load the wrong resource.

I tried this with a newer clone of Chalk and still received the same errors (gh-pages trying to pull css/js resources from `name-long_string_of_hex.js`. Any help?

**Comment by nielsenramon** [comment]
@nbulischeck Did you see the important note here: https://github.com/nielsenramon/chalk/blob/master/README.md#deploy-to-github-pages ?

I think that will solve your issue!

**Comment by nbulischeck** [comment]
@nielsenramon Yes I've ran that and it hasn't worked recently. I have [successfully built Chalk in the past](https://nbulischeck.io/), so I wouldn't say I'm new at your build system, but I could definitely be doing something wrong.

Testing Repo: https://github.com/nbulischeck/chalk-testing

Steps to reproduce:

```
git clone https://github.com/nielsenramon/chalk.git
cd chalk
git remote set-url origin git@github.com:nbulischeck/chalk-testing.git
git push -u origin master
npm run publish
```

Result: https://nbulischeck.github.io/chalk-testing/

**Comment by nbulischeck** [comment]
The `light-*.css` file is prevalent, but it's in `/assets/`, not the root directory (see here https://github.com/nbulischeck/chalk-testing/blob/gh-pages/assets/light-66f45f496d3d18e5d0be0a1c4197083526ac584c945d0ef492f7375867f3b191.css).

I re-ran `npm run publish` with the same results.

**Comment by migueldemoura** [comment]
You're right, didn't notice the dir.

Try setting the baseurl: https://github.com/nbulischeck/chalk-testing/blob/master/_config.yml#L12 :smile:

**Comment by nbulischeck** [comment]
That was it! What a simple solution :laughing:. I would recommend that be added to the important note. Something along the lines of:

> Make sure to set your `baseurl` in `_config.yml` as the name of your github repo.

**Comment by migueldemoura** [comment]
You can probably send in a PR with that notice. Is the website always deployed to a subfolder using GH-Pages? Thought I'd seen others without it.

**Comment by nbulischeck** [comment]
Only if it's a project site.

If you're building it for a project site, then it will be at <user/organization>.github.io/<repo-name>.

If you're building it for a user or organization site, then it will be at <user/organization>.github.io/

I'll send in a PR shortly.

**Comment by nielsenramon** [comment]
@migueldemoura I was hesitant to add it as it's basic Jekyll functionality but I'll accept the PR!

Glad it's fixed ;-)

**Comment by nielsenramon** [comment]
PR merged thanks!
