### ISSUE TITLE
Ran bin/deploy before pushing or committing changes. Now certain files are deleted and cannot revert changes.

### ISSUE THREAD

**Issue by BTPhysics** [nielsenramon/chalk#158]
Basically when I finished working on my copy of the site, I ran git init and then run/deploy. 

So when I ran run/deploy, I got this error message back: https://pastebin.com/MZPGvstX It also deleted a bunch of my files and I'm so confused as to what happened. I really hope I can at least recover it.

It's quite odd, because bin/deploy only deletes unimportant files such as _sites and .gitignore, etc. But it deleted the layouts folder for me and the scss files under assets, along with many others. No commits seem to have been made, but I still can't go back. Also I can't go back to the main branch, I'm stuck on the gh-pages branch.

**Comment by xRahul** [comment]
I've looked at the logs you've pasted. Actually, you need to have the remote setup correctly and have to commit your changes before trying to deploy them.

You do not have the correct remote origin setup and also you should commit your changes before deploying.

**Comment by nielsenramon** [comment]
@BTPhysics Indeed, very important to commit your changes before deploying!
