### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jesster2k10** [nielsenramon/chalk#16]
How can I install this on my site. 
I'm so stuck. Please help s your guide is too  vague. Itried following this but I get an error http://jekyllbootstrap.com/usage/jekyll-theming.html

    No such file or directory @ rb_sysopen - ./_theme_packages/_tmp/manifest.yml

**Comment by nielsenramon** [comment]
@jesster2k10 Please follow the exact same instructions from the readme file. I do not use the way you linked me ;)
