### ISSUE TITLE
More of a question than an issue: What specific plugins are unsupported by github?

### ISSUE THREAD

**Issue by BTPhysics** [nielsenramon/chalk#179]
I'd rather host the repository on github and have it build the page rather than build the page locally and push the /sites folder. What are the plugins that are unsupported by github, and are they essential to Chalk? Are there ways to uninstall it so that I can be able to push the repo rather than the locally generated page?

**Comment by nielsenramon** [comment]
It's definitely something I wish to do when I have the time. Jekyll-assets is not supported for example and it's a big part of this theme. 

marking this as closed as there is a discussion about this here: https://github.com/nielsenramon/chalk/issues/144
