### ISSUE TITLE
Invalid Tags

### ISSUE THREAD

**Issue by jesster2k10** [nielsenramon/chalk#18]
I made an article following your sample one. You can check it out on my repo [here](https://github.com/jesster2k10/jesster2k10.github.io) this is what I get on my github account:

    Your site is having problems building: The tag asset_path on line 1 in _posts/2016-11-28-user-login-sign-up-using-firebase-in-swift-3.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

**Comment by nielsenramon** [comment]
@jesster2k10 Have you run bin/setup? Check if jekyll-assets is installed please.

**Comment by jesster2k10** [comment]
yea i have, ill run again

**Comment by jesster2k10** [comment]
This is my log output:

Jesses-iMac:chalk-master 3 jeffe$ bin/setup
The Gemfile's dependencies are satisfied
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.......
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using execjs 2.7.0
Using colorator 1.1.0
Using colored 1.2
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using mercenary 0.3.6
Using mini_portile2 2.1.0
Using parallel 1.10.0
Using yell 2.0.7
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.13.1
Using liquid 3.0.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.5
Using jekyll-paginate 1.1.0
Using mini_magick 4.5.1
Using bundler 1.13.6
Using tzinfo 1.2.2
Using addressable 2.5.0
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.3
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using extras 0.1.0
Using pathutil 0.14.0
Using nokogiri 1.6.8.1
Using jekyll-sass-converter 1.5.0
Using sprockets 3.6.3
Using activesupport 5.0.0.1
Using fastimage 2.0.1
Using typhoeus 0.8.0
Using listen 3.0.8
Using html-proofer 3.3.1
Using jekyll-watch 1.5.0
Using jekyll 3.3.1
Using jekyll-assets 2.2.8
Using jekyll-sitemap 0.12.0
Bundle updated!
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/jeffe/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/bower
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── bower@1.8.0 

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/bower' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeffe/Downloads/chalk-master 3/npm-debug.log
Jesses-iMac:chalk-master 3 jeffe$

**Comment by jesster2k10** [comment]
I tried with sudo

Jesses-iMac:chalk-master 3 jeffe$ sudo bin/setup
Password:
The Gemfile's dependencies are satisfied
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using execjs 2.7.0
Using colorator 1.1.0
Using colored 1.2
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using mercenary 0.3.6
Using mini_portile2 2.1.0
Using parallel 1.10.0
Using yell 2.0.7
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.13.1
Using liquid 3.0.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.5
Using jekyll-paginate 1.1.0
Using mini_magick 4.5.1
Using bundler 1.13.6
Using tzinfo 1.2.2
Using addressable 2.5.0
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.3
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using extras 0.1.0
Using pathutil 0.14.0
Using nokogiri 1.6.8.1
Using jekyll-sass-converter 1.5.0
Using sprockets 3.6.3
Using activesupport 5.0.0.1
Using fastimage 2.0.1
Using typhoeus 0.8.0
Using listen 3.0.8
Using html-proofer 3.3.1
Using jekyll-watch 1.5.0
Using jekyll 3.3.1
Using jekyll-assets 2.2.8
Using jekyll-sitemap 0.12.0
Bundle updated!
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

and I tried with --allow-root but it's the same

the project works fine locally 

https://drive.google.com/file/d/0B2sTu4QD_nWLM0pFLWxnZnVmX0k/view?usp=sharing

there's the log file

**Comment by nielsenramon** [comment]
@jesster2k10 Can you check if `bower install` works fine?

**Comment by jesster2k10** [comment]
Jesses-iMac:chalk-master 3 jeffe$ bower install
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/jeffe/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by nielsenramon** [comment]
Yeah you have to fix your bower setup first I'm afraid. Try reinstalling without sudo.

**Comment by jesster2k10** [comment]
Jesses-iMac:chalk-master 3 jeffe$ sudo bower install
Password:
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

**Comment by jesster2k10** [comment]
I ran this and nothing came out 

   sudo bower install --allow-root

**Comment by nielsenramon** [comment]
Try without sudo, looks like your bower installation is kinda broken. Can't help you with that I'm afraid ;-)

**Comment by irasuna** [comment]
@jesster2k10 edit the last line of your bin/setup file to be
```
bower install --allow-root
```

and run `sudo bin/setup`. If you still encounter error, try to copy whatever inside `bower_component/` into `_assets/bower/`. Now you should be able to run the web locally. To deploy, run `sudo bin/deploy` but then again you should modify the lines in the bin/deploy file that says `bower install` into `bower install --allow-root`. Hope this helps 👍

**Comment by jesster2k10** [comment]
it worked!

**Comment by jesster2k10** [comment]
when I run bin/deploy i get 

Cannot delete branch 'gh-pages' checked out at '/Users/jeffe/Downloads/chalk-master 3'

**Comment by jesster2k10** [comment]
when i run bin/deploy i get

fatal: A branch named 'gh-pages' already exists.

**Comment by jesster2k10** [comment]
Jesses-iMac:chalk-master 3 jeffe$ sudo bin/deploy
Password:
Started deploying
M	bin/deploy
M	bin/setup
Switched to a new branch 'gh-pages'
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

**Comment by jesster2k10** [comment]
where's the bower compenent?

**Comment by irasuna** [comment]
@jesster2k10 first you need to go back to your master branch, then delete your gh-pages branch
``` git
git checkout master
git branch -d gh-pages
```
now you should be able to run `sudo bin/deploy`. If you don;t see your web after doing so, try to merge your gh-pages into your master branch
```
git checkout master
git merge gh-pages
```

and as I told you before, edit all the the line in the bin/deploy file that says `bower install` into `bower install --allow-root`. Then run `sudo bin/deploy`

The `bower_component/` is in your main folder along with `_assets`, `bin` and other folders and files. If you don't see this folder, most probably it is already in your `_assets/bower/` folder.

**Comment by jesster2k10** [comment]
I still have the same issue even if I added the --allow-root in the deploy. there's no `bower_component` at all in my folder. And it's not in my `_assests/bower`. For some strange reason, bin/setup works and bin/deploy doesn't

**Comment by ewnit** [comment]
I also got this problem.  
```
The tag `asset_path` on line 13 in `/_layouts/post.html` is not a recognized Liquid tag. 
```

**Comment by nielsenramon** [comment]
`asset_path` is from the jekyll-assets gem. What version of Ruby are you using? Is everything correctly installed? If you don't have `_assets/bower` there is something wrong with your bower installation.

**Comment by ewnit** [comment]
here is my `ruby --version` output and my `bower install` works fine, `_assets/bower` exists too:

```
~/Documents/ewnit.github.io  master ✔
▶ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

~/Documents/ewnit.github.io  master ✔                                                                                                                 10m
▶ bower install

ewnit.github.io/_assets/bower  master ✔                                                                                                               12m
▶ ll
total 0
drwxr-xr-x  13 cyan  staff   442B 11 29 17:30 fluidbox
drwxr-xr-x  10 cyan  staff   340B 11 29 17:30 jquery
drwxr-xr-x   8 cyan  staff   272B 11 29 17:30 scrollreveal
```

**Comment by jesster2k10** [comment]
there's assets/bower and inside theres fluidbox jquery and scrollreveal

**Comment by jesster2k10** [comment]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

that's my ruby version

**Comment by jesster2k10** [comment]
I downgraded my ruby version to 2.3.0, update brew and followed this https://github.com/bower/bower/issues/2262

My `bower install` works however, I'm getting this error now 

/Users/jeffe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/jeffe/.rvm/gems/ruby-2.3.0:/Users/jeffe/.rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
	from /Users/jeffe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /Users/jeffe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Users/jeffe/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'

**Comment by jesster2k10** [comment]
I'll try run bin/setup again, see if that fixes it

**Comment by jesster2k10** [comment]
Ran set up and it deployed successfully, time to check the site

**Comment by jesster2k10** [comment]
M site works, but it's now HTML and not .md how can I edit it or make posts now?

**Comment by jesster2k10** [comment]
my bad, forgot to push before deploy

**Comment by jesster2k10** [comment]
can you check if i've done everything right? My site shows up as not found

https://github.com/jesster2k10/jesster2k10.github.io

**Comment by jesster2k10** [comment]
When I run `bin/setup` it works successfully but I see the following warnings

     bower invalid-meta  for:/var/folders/w_/3clcl4bs3sz2dr69fqr458zr0000gn/T/jeffe/bower/75bc45a9b7382783b733434da90458e5-89972-BJ664r/bower.json
    bower invalid-meta  The "main" field cannot contain minified files
    bower invalid-meta  The "main" field cannot contain minified files
    bower mismatch      Version declared in the json (2.0.0) is different than the resolved one (2.0.4).

When I run `bin/deploy` it work sucessfully but the invalid tags error still persists.

**Comment by nielsenramon** [comment]
@ewnit Can you verify that you installed jekyll-assets on ruby 2.3.0 please and that you ran bundle install?
@jesster2k10 I have no idea what is going on with your bower installation. Did you reinstall properly? It looks like you have multiple versions running?

**Comment by ewnit** [comment]
```
▶ bundle install
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using execjs 2.7.0
Using colorator 1.1.0
Using colored 1.2
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using mercenary 0.3.6
Using mini_portile2 2.1.0
Using parallel 1.9.0
Using yell 2.0.7
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.12.0
Using liquid 3.0.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.5
Using jekyll-paginate 1.1.0
Using mini_magick 4.5.1
Using bundler 1.13.6
Using tzinfo 1.2.2
Using addressable 2.5.0
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.3
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using extras 0.1.0
Using pathutil 0.14.0
Using nokogiri 1.6.8.1
Using jekyll-sass-converter 1.4.0
Using sprockets 3.6.3
Using activesupport 5.0.0.1
Using fastimage 2.0.1
Using typhoeus 0.8.0
Using listen 3.0.8
Using html-proofer 3.3.1
Using jekyll-watch 1.5.0
Using jekyll 3.3.0
Using jekyll-assets 2.2.8
Using jekyll-sitemap 0.12.0
Bundle complete! 9 Gemfile dependencies, 44 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

I'm not quite familiar with this, does `Using jekyll-assets 2.2.8` prove I have installed it

**Comment by nielsenramon** [comment]
@ewnit jep looking good. Still same error? Is your repo open source so I can check it?

**Comment by ewnit** [comment]
@nielsenramon yes, same problem, you can check my repo [ewnit.github.io](https://github.com/ewnit/ewnit.github.io).

**Comment by EQuimper** [comment]
+1 I got this me too and run all what people say here and still have error :(

**Comment by nielsenramon** [comment]
@ewnit Just checked out your code and ran bin/setup. Had no issues. 

![screen shot 2016-12-12 at 13 49 16](https://cloud.githubusercontent.com/assets/1246672/21099978/a5ec9428-c071-11e6-934b-444ede1e1bc5.png)

Can you all make sure that bower and ruby are installed correctly. If not I recommend you setting up your computer with a proper laptop script.

**Comment by ewnit** [comment]
@nielsenramon This also runs well on my computer, but running `bin/deploy` just can't set up my page correctly on git pages. Trying to find out what was going on I changed my code on origin/master and received the mail from github said The tag `asset_path` on line 13 in `/_layouts/post.html` is not a recognized Liquid tag. `

```
▶ bundle exec jekyll serve
Configuration file: /Users/it/Documents/ewnit.github.io/_config.yml
Configuration file: /Users/it/Documents/ewnit.github.io/_config.yml
            Source: /Users/it/Documents/ewnit.github.io
       Destination: /Users/it/Documents/ewnit.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.036 seconds.
 Auto-regeneration: enabled for '/Users/it/Documents/ewnit.github.io'
Configuration file: /Users/it/Documents/ewnit.github.io/_config.yml
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
```

**Comment by nielsenramon** [comment]
@ewnit Aaah of course you get that email. GitHub can't work with jekyll-assets. That's why there is a  deploy script which pushes the output to gh-pages branch. I advise you to change the branch name from master to something else to avoid these emails. Or rename your repo so it does not contain: github.io

**Comment by ewnit** [comment]
@nielsenramon Understand now. Thank you so much! All I have to do is to merge `gh-pages` to `master` and the github.io page will show correctly.

**Comment by nielsenramon** [comment]
Yeah and use an other branch for your jekyll project of course ;-)

**Comment by EQuimper** [comment]
Work for me now, yes I got this email and didn't figure out. Thank you @nielsenramon
