### ISSUE TITLE
Question about New Posts

### ISSUE THREAD

**Issue by karanchawla** [nielsenramon/chalk#189]
Hi,

I'm super new to hosting via Github and web technologies in general. Sorry if this is a stupid question but I'm trying to create new posts by creating a markdown in the directory posts (this right now is basically a copy of one of the sample posts with a different name). However, it doesn't show up when I deploy the website. I notice that the corresponding html for the post isn't generated under the `_site` directory. 

What am I doing wrong? Do I have to register the name of this markdown in some other file?

**Comment by enzoftware** [comment]
Hi, same issue here. @karanchawla how you solve this?
