### ISSUE TITLE
Liquid Exception: Couldn't find file '{{ include.icon }}' in /_layouts/post.html

### ISSUE THREAD

**Issue by thedan84** [nielsenramon/chalk#192]
Help.
For a couple of days I'm getting the error above when I try to run `npm run local` or `npm run publish`. I haven't changed anything about the layouts or includes if that helps.
Thanks in advance.

**Comment by artis3n** [comment]
I'm seeing this as well with `npm run local` for `{{ include.path-detail }}`.

**Comment by kumar1202** [comment]
` Liquid Exception: Couldn't find file '{{ include.path-detail }}' in C:/chalk/_posts/2017-12-21-chalk-sample-post-with-all-elements.md`
Getting this while running `npm run local`

**Comment by nielsenramon** [comment]
I had to fix the version of Jekyll to 3.8.x as jekyll-assets doesn't support 4.0 yet :-/ So now it should be solved!
