### ISSUE TITLE
A problem with the font

### ISSUE THREAD

**Issue by fuyw** [nielsenramon/chalk#22]
I like chalk a lot, and I met a problem with the font display.

Font of the blog title is different when I deploy to github, and it works fine when I "jekyll serve" locally.

<img width="134" alt="screen shot 2016-12-05 at 5 31 32 pm" src="https://cloud.githubusercontent.com/assets/23493245/20879916/dc6605ae-bb10-11e6-9c0c-cfd6514b4188.png">

<img width="148" alt="screen shot 2016-12-05 at 5 31 17 pm" src="https://cloud.githubusercontent.com/assets/23493245/20879915/dc30b62e-bb10-11e6-9e20-67d773e9ca69.png">

I have found a difference of the html tag, some values become inactivate.

runs at gitbub:
<img width="646" alt="screen shot 2016-12-05 at 6 19 27 pm" src="https://cloud.githubusercontent.com/assets/23493245/20881470/76067238-bb17-11e6-9891-ae0107a14e73.png">

runs locally:
<img width="652" alt="screen shot 2016-12-05 at 6 19 17 pm" src="https://cloud.githubusercontent.com/assets/23493245/20881487/8ab4176c-bb17-11e6-99eb-c5d16278a644.png">

But I have no idea why this happen, and how to fix it.

Any one can help, many thanks.

Additionally, the problem is with Firefox and Safari, Chrome works fine.

**Comment by fuyw** [comment]
I have found a difference of the html tag, some values become inactivate.

runs at gitbub:
<img width="646" alt="screen shot 2016-12-05 at 6 19 27 pm" src="https://cloud.githubusercontent.com/assets/23493245/20881470/76067238-bb17-11e6-9891-ae0107a14e73.png">

runs locally:
<img width="652" alt="screen shot 2016-12-05 at 6 19 17 pm" src="https://cloud.githubusercontent.com/assets/23493245/20881487/8ab4176c-bb17-11e6-99eb-c5d16278a644.png">

But I have no idea why this happen, and how to fix it.

Any one can help, many thanks.

**Comment by nielsenramon** [comment]
@fuyw Is your website open source so I can have a look? I can't replicate the issue.
