### ISSUE TITLE
How to use the about page?

### ISSUE THREAD

**Issue by xrisk** [nielsenramon/chalk#23]
It seems there is no link to the about page other than a small link in the footer... Is there some way to add it to the navbar?

**Comment by nielsenramon** [comment]
@xrisk You could alter the code to do so :)
I'll think about a secondary way to access it. Thanks for the heads up.

**Comment by ewnit** [comment]
@xrisk I diy it and add a small smile-face to the navbar, you can check my code.

**Comment by nielsenramon** [comment]
@xrisk @ewnit I added a setting and link in the navigation ;-)

**Comment by xrisk** [comment]
Great stuff. Thanks!

**Comment by ZhuZeus** [comment]
Failed to run on GitHub.... it seems looks like jekyll has a problem.Can you help me about that?

**Comment by nielsenramon** [comment]
@ZhuZeus Can you define the problem please?

**Comment by ZhuZeus** [comment]
localhost just fine..this the issue from github<Your site is having problems building: The tag asset_path on line 1 in _posts/2016-10-15-chalk-sample-post-with-all-elements.md is not a recognized Liquid tag. For more information>, thanks a lot

**Comment by nielsenramon** [comment]
@ZhuZeus GitHub can't work with jekyll-assets. That's why there is a deploy script which pushes the output to gh-pages branch. I advise you to change the branch name from master to something else to avoid these emails. Or rename your repo so it does not contain: github.io

**Comment by ZhuZeus** [comment]
@nielsenramon got it ,thank you very much
