### ISSUE TITLE
fluidbox.scss import error

### ISSUE THREAD

**Issue by djacquel** [nielsenramon/chalk#27]
Once installed `bundle exec jekyll serve` return a scss import error ([see](http://stackoverflow.com/questions/41204946/jekyll-serve-not-working-cannot-find-fluidbox-scss)).

> Error in _assets/stylesheets/light.scss:50 File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.
> ...

Install process needs to include `bower install`.

**Comment by nielsenramon** [comment]
It does if you run `bin/setup` https://github.com/nielsenramon/chalk/blob/master/bin/setup#L16
