### ISSUE TITLE
Posts not appearing on page.

### ISSUE THREAD

**Issue by christiantype** [nielsenramon/chalk#28]
Hi, it's me again.

I'm working on an online portfolio that uses your Chalk Theme and have made my `index.html ` to only include posts with the tag `project`. I did this by making my `index.html` include the following:

```
    {% for post in site.tags.project %}



    <li class="block">
        <a href="{{ post.url | relative_url }}" title="{{ post.title }}">

            <img src="./assets/projects/{{ post.image }}"/>

        </a>


    </li>
    {% endfor %}
```

All other posts I want to be shown on a page which I named `journal.html`. On this page, I pretty much left all the same content that your `index.html` includes.

However, when I preview the `journal.html`, no posts are shown.

Here's my repository https://github.com/christiantype/christian-thoughts
and here's the live site: http://christiansolorzano.com/journal/

Thank you

**Comment by nielsenramon** [comment]
I only provide support for my own theme. I can't fix everyone's custom themes ;-)
Looks like you are bending the tags to much in there.
