### ISSUE TITLE
jekyll 3.3.1 support ?

### ISSUE THREAD

**Issue by sandys** [nielsenramon/chalk#32]
hi,
the new jekyll 3.3 (and forward) uses gem based themes. are you planning to support this or will you only support older jekyll versions ?

**Comment by nielsenramon** [comment]
@sandys I support the latest version of Jekyll. I just cannot use the gem based theme as Jekyll does not support certain plugins I use like `jekyll-assets` + the deployment scripts. I always keep an eye out to when jekyll-assets would be supported tho.

Any specific reason why you would want the gem based theme?

**Comment by sandys** [comment]
well we are using the newer jekyll versions and the recommended way is to
use the themes

**Comment by nielsenramon** [comment]
@sandys As I said the way Chalk is built it is not possible to use the Jekyll theming gem. You can always use the latest version of Jekyll regardless of that.
