### ISSUE TITLE
Error on bundle exec jekyll serve

### ISSUE THREAD

**Issue by hubertron** [nielsenramon/chalk#34]
Following these steps:

1. Clone Repo
2. `bin/setup`
3. `bundle exec jekyll serve`

This error manifests: 
`Error in _assets/stylesheets/light.scss:50 File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.`

Ruby Version: `Ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]`
NPM Version: `3.10.3`

Issue also experience by others here: [http://stackoverflow.com/questions/41204946/jekyll-serve-not-working-cannot-find-fluidbox-scss/41468876#41468876](http://stackoverflow.com/questions/41204946/jekyll-serve-not-working-cannot-find-fluidbox-scss/41468876#41468876)

**Comment by hubertron** [comment]
I was able to fix this by running this in a new directory. It appears that using an existing jekyll project will cause this error do  to a difference in .rbenv settings from a basic `jekyll new` vs this repo's `bin/setup` 

It might be worth mentioning in your readme that this should be only used for new projects and not added to existing ones that your listings of Chalk in "theme" websites would suggest would be ok. All in all the code looks great and is very clean and logical.  Thank you for creating this and obviously putting some love into it.

**Comment by nielsenramon** [comment]
@hubertron The only reason why it failed was because you were missing bower I think? Or that you did not include the `.bowerrc` file?

Thanks for the nice words!

**Comment by hubertron** [comment]
It's certainly possible I was missing it, but wouldn't have that come through from a `.gitclone` and `bundle install` take care of installing anything else I needed?
