### ISSUE TITLE
I have problem with Chalk, please help

### ISSUE THREAD

**Issue by Crypto-Nik** [nielsenramon/chalk#37]
I had a mistake:
Your site is having problems building: The tag asset_path on line 1 in _posts / 2016-10-15-chalk-sample-post-with-all-elements.md is not a recognized Liquid tag.

**Comment by nielsenramon** [comment]
@Crypto-Nik  GitHub can't work with jekyll-assets. That's why there is a deploy script which pushes the output to gh-pages branch. I advise you to change the branch name from master to something else to avoid these emails. Or rename your repo so it does not contain: github.io
