### ISSUE TITLE
Receiving warning when running Jekyll Serve

### ISSUE THREAD

**Issue by christiantype** [nielsenramon/chalk#4]
`Christians-MacBook-Pro:chalk-master christians$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/christians/Documents/chalk-master/_config.yml
Configuration file: /Users/christians/Documents/chalk-master/_config.yml
            Source: /Users/christians/Documents/chalk-master
       Destination: /Users/christians/Documents/chalk-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.814 seconds.
 Auto-regeneration: enabled for '/Users/christians/Documents/chalk-master'
Configuration file: /Users/christians/Documents/chalk-master/_config.yml
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-11-06 08:43:54 ...done in 0.358506 seconds.`

**Comment by nielsenramon** [comment]
@christiantype Did you run `bin/setup`? Any errors during setup? Ruby version?

**Comment by littletiger666** [comment]
When I try to run 
`bundle exec jekyll serve`
I got this error:
<img width="914" alt="screenshot 2016-11-08 10 32 18" src="https://cloud.githubusercontent.com/assets/9539036/20111917/f5796540-a59e-11e6-9930-c2cbe9e6bf7f.png">

I already run `bin/setup` and `bundle install`, there were no errors.

**Comment by nielsenramon** [comment]
It looks like you cannot find the required fluidbox css in your project.
Can you check if you have the file in `_assets/bower/fluidbox` please?

**Comment by littletiger666** [comment]
No I can't find `_assets/bower/fluidbox` file

**Comment by nielsenramon** [comment]
Can you check what happens when you run `bower install`? Also please check if you have a `.bowerrc` file in the root folder.

**Comment by littletiger666** [comment]
It worked after I run `bower install`! 
The reason it didn't work it that I didn't install npm and bower.
Thank you very much!

**Comment by christiantype** [comment]
All is working fine now. Thanks everybody
