### ISSUE TITLE
install Error in Windows Platform missing files

### ISSUE THREAD

**Issue by aboutyy** [nielsenramon/chalk#44]
details of the errors are listed below：
PS D:\MyWebsite\blog1> bower install
bower fluidbox#~2.0.4           ENOGIT git is not installed or not in the PATH
PS D:\MyWebsite\blog1> bundle exec jekyll serve
Configuration file: D:/MyWebsite/blog1/_config.yml
Configuration file: D:/MyWebsite/blog1/_config.yml
            Source: D:/MyWebsite/blog1
       Destination: D:/MyWebsite/blog1/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Error in _assets/stylesheets/light.scss:50 File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.
Load paths:
  D:/MyWebsite/blog1/_assets/css
  D:/MyWebsite/blog1/_assets/stylesheets
  D:/MyWebsite/blog1/_assets/images
  D:/MyWebsite/blog1/_assets/img
  D:/MyWebsite/blog1/_assets/fonts
  D:/MyWebsite/blog1/_assets/javascripts
  D:/MyWebsite/blog1/_assets/js
  D:/MyWebsite/blog1/_assets/bower
  D:/MyWebsite/blog1/_vendor
  Liquid Exception: File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss. Load paths: D:/MyWebsite/blog1/_assets/css D:/MyWebsite/blog1/_assets/stylesheets D:/MyWebsite/blog1/_assets
/images D:/MyWebsite/blog1/_assets/img D:/MyWebsite/blog1/_assets/fonts D:/MyWebsite/blog1/_assets/javascripts D:/MyWebsite/blog1/_assets/js D:/MyWebsite/blog1/_assets/bower D:/MyWebsite/blog1/_vendor in /_layo
uts/post.html
jekyll 3.3.1 | Error:  File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.
Load paths:
  D:/MyWebsite/blog1/_assets/css
  D:/MyWebsite/blog1/_assets/stylesheets
  D:/MyWebsite/blog1/_assets/images
  D:/MyWebsite/blog1/_assets/img
  D:/MyWebsite/blog1/_assets/fonts
  D:/MyWebsite/blog1/_assets/javascripts
  D:/MyWebsite/blog1/_assets/js
  D:/MyWebsite/blog1/_assets/bower
  D:/MyWebsite/blog1/_vendor

**Comment by nielsenramon** [comment]
@aboutyy Did you install npm and bower? Can you check if bower installed your files correctly under _assets?

**Comment by aboutyy** [comment]
@nielsenramon yes, it seems that i did not install the files correctly before, the problem is solved now. thanks
