### ISSUE TITLE
Change head icon

### ISSUE THREAD

**Issue by albertoalegria** [nielsenramon/chalk#45]
I'm trying to change the head icon. I want to put a custom icon instead of the letter C icon. Please understand that my html knowledges are pretty basic.

**Comment by migueldemoura** [comment]
I'm assuming you meant the favicon. That can be modified by changing these two files:
[`/favicon.ico`](https://github.com/nielsenramon/chalk/blob/master/favicon.ico)
[`/_assets/images/apple-touch-icon.png`](https://github.com/nielsenramon/chalk/blob/master/_assets/images/apple-touch-icon.png)

Please note the image dimensions.

**Comment by nielsenramon** [comment]
@migueldemoura Is correct, make sure your favicon is 32x32 and apple-touch-icon.png is 180x180.

**Comment by albertoalegria** [comment]
It's fixed, thank you
