### ISSUE TITLE
Feature: Post Previews

### ISSUE THREAD

**Issue by sammcj** [nielsenramon/chalk#46]
Howdy, Thanks for building this pretty little theme :)

It would be neat if you could set a number of lines for Chalk to preview of a post.

In the past I've used the [excerpt_separator](http://wesleytsai.io/2015/07/06/create-post-previews-for-jekyll-blogs/) on my posts with other themes.

Do you think this would that be something you could easily add in into the theme?

Thanks,

**Comment by nielsenramon** [comment]
@sammcj Can you show a visual example of this please?

**Comment by migueldemoura** [comment]
Maybe this:

[https://wesleytsai.io/](https://wesleytsai.io/)

**Comment by nielsenramon** [comment]
@sammcj @migueldemoura I don't see what the difference is with the current description?

**Comment by migueldemoura** [comment]
Don't you have to manually specify such "preview" with Chalk?

**Comment by nielsenramon** [comment]
@sammcj I prefer to manually enter the preview so you have more control over it.
