### ISSUE TITLE
In feed.xml, why site.url always is http://localhost:4000?

### ISSUE THREAD

**Issue by ArchimboldiMao** [nielsenramon/chalk#48]
I followed the Usage to Installation & Development.
1. Set url: http://domain.com in _config.yml, 
2. Run bundle exec jekyll serve -w
3. Use chrome open http://127.0.0.1:4000/feed.xml
I think the link should be <link>http://domain.com/</link>, but it always is <link>http://localhost:4000</link>, whatever is set any value to url: in _config.yml.

**Comment by nielsenramon** [comment]
@ArchimboldiMao In the production version it will be your url. Example: http://chalk.nielsenramon.com/feed.xml

**Comment by ArchimboldiMao** [comment]
Thanks for your guide.
Now I know why and how to do, and I should run this: JEKYLL_ENV=production bundle exec jekyll serve

**Comment by TommyWhite** [comment]
I wasted over 2 evenings to found out that NGINX reverse proxy is not responsible for redirection to localhost. 
So, `JEKYLL_ENV-production jekyll server`
Thanks, man

**Comment by migueldemoura** [comment]
@nielsenramon, should probably add this to the docs - it isn't obvious.

**Comment by designbymichael** [comment]
I agree with @migueldemoura.  Seems to me that this thing should populate the feed.xml with the production URL unless you explicitly define so.
