### ISSUE TITLE
Cannot remote display the website

### ISSUE THREAD

**Issue by Elitack** [nielsenramon/chalk#52]
I follow the order of the document. And I'v finished that I can see the website locally by executing 
```shell
bundle exec jekyll serve
```
But at the last step, when I exec the deploy file, it shows

```shell
Permission denied(publickey)
fatal:could not read from the remote repository
```

And I check the deploy file, I found that the file is aimed to operate the gh-pages branch.
But I just wanna display the website on my [homepage](elitack.github.io) so I just need the master branch is enough. So I just simply push the code on master branch. But when I visit the [my homepage](elitack.github.io), it shows nothing.

Here is what I put on [my github](http://github.com/elitack/Elitack.github.io.git).

**Comment by Elitack** [comment]
ps, I got many error emails from the github, all mails show like it cannot recognize the liquid tag:
+ The tag `asset_path` on line 1 in `_posts/2016-10-15-chalk-sample-post-with-all-elements.md` is not a recognized Liquid tag. 

+ A file was included in `_posts/2016-10-15-chalk-sample-post-with-all-elements.md` that is a symlink or does not exist in your `_includes` directory.

+ The tag `stylesheet` on line 10 in `404.html` is not a recognized Liquid tag

**Comment by Elitack** [comment]
Ah..I try a method that builds locally and include the results in the Pages repository..Then it worked. I guess the model you produce got some unrecognized tags so that we have to build it locally...And then submit the after-build files.

**Comment by nielsenramon** [comment]
@Elitack indeed you should be working on another branch than master and make sure you deploy the output files to the master branch. I need to add some documentation for people who use a github.io repo as that works differently.
