### ISSUE TITLE
unable to apply dark theme on github pages

### ISSUE THREAD

**Issue by KST123ABC** [nielsenramon/chalk#53]
including `blog_theme: dark` in config, no results on github pages after build. Still light theme.

Built on windows 10.

First issue so lmk if I need to supply more.

**Comment by nielsenramon** [comment]
@KST123ABC do you get the dark theme locally? Remember that chalk does not support standard Jekyll hosting as it is using unsupported plugins.

**Comment by KST123ABC** [comment]
@nielsenramon thanks for responding.
I may be doing something wrong as this is my first time using a Jekyll theme that is unsupported. 

Is there a different repo for the dark theme?
I cloned this repo, edited the config, and then attempted to generate the site.

Thanks for your help! :)

**Comment by nielsenramon** [comment]
@KST123ABC Did you execute the installation instructions which is stated in the readme of Chalk? And did you manage to run your project locally?

**Comment by KST123ABC** [comment]
@nielsenramon I have been the README. I receive an error now when I run the Jekyll bundle server command 

![jekbun](https://cloud.githubusercontent.com/assets/5109500/23304330/39400d48-fa67-11e6-8ba1-25925bb1261f.PNG)

**Comment by nielsenramon** [comment]
@KST123ABC That error is about a file you are referencing and jekyll can't find it.

**Comment by KST123ABC** [comment]
@nielsenramon hello. I do not believe I added any references to other files. I haven't modified anything in this pull.

**Comment by KST123ABC** [comment]
I may try it on my Linux machine rather than windows... will keep you posted.

**Comment by nielsenramon** [comment]
Weird: icon-github.html is not a file in Chalk. :-p

**Comment by KST123ABC** [comment]
Hey @nielsenramon sorry it took me so long to get back to this. I have been quite busy.
Was never able to get it to build the site files on Windows using Chocolatey but I have had success on Linux.

I am quite new to Jekyll so excuse me if I botch the terminology here.

Attached I have included the successfully hosted site.
When viewing the site on any platform besides for Windows Internet Explorer, the included icon assets for the personal account portion of the theme seem to be inable to display. It looks quite the same on Macintosh osx's various browsers. I was wondering if this problem has been raised.

Again, appologies for my novice-ness and delayed response. 
The listed images are examples of chrome on linux, mozilla firefox on windows, and finally IE on windows.

Please let me know if I can be of any help.
![chrome linux](https://cloud.githubusercontent.com/assets/5109500/24876528/0a8a2ad6-1dfa-11e7-9247-115db656d3c2.png)
![mozff windows](https://cloud.githubusercontent.com/assets/5109500/24876529/0a8a6032-1dfa-11e7-9d41-1c77132fab80.PNG)
![ie windows](https://cloud.githubusercontent.com/assets/5109500/24876527/0a894d1e-1dfa-11e7-8a15-8690dc95cf3e.PNG)

**Comment by nielsenramon** [comment]
@KST123ABC Should be fixed now with latest version on master!

**Comment by KST123ABC** [comment]
![2017-04-25-115834_2048x1152_scrot](https://cloud.githubusercontent.com/assets/5109500/25395373/dd753a0c-29ae-11e7-9b51-f0c067427eb8.png)

@nielsenramon thanks for the update! Just pulled from master and tried but the icons don't seem to be working. I then downloaded the .woff and .ttf from the source repo https://github.com/driftyco/ionicons

put those in _site/assets/ionicons/* and now the icons appear to work.
