### ISSUE TITLE
A subtler quote?

### ISSUE THREAD

**Issue by nistara** [nielsenramon/chalk#54]
Thanks for the great template. I ran into your site while searching for a clean, minimal, and tasteful layout. With this in mind, do you think it's possible to make the quote sections subtler? Something like this: https://zenhabits.net/powerful-stillness/

**Comment by nistara** [comment]
I was able to modify it in the _base.scss file. I'm slowly learning the elements!

**Comment by nielsenramon** [comment]
@nistara Glad to hear!
