### ISSUE TITLE
The tag `stylesheet` on line 10 in `blog/404.html` is not a recognized Liquid tag.

### ISSUE THREAD

**Issue by huyanhh** [nielsenramon/chalk#55]
I am trying to use the blog as a subdirectory to my normal website. I have the structure like this:

![screen shot 2017-02-22 at 2 56 47](https://cloud.githubusercontent.com/assets/15709918/23208637/a0487a7a-f8aa-11e6-83e9-d51f3b0d5fe0.png)

and my _config.yml is as follows:

```
name: Huyanh Hoang
paginate: 25
paginate_path: "/posts/page/:num/"
url: https://huyanhhoang.co
baseurl: /blog
blog_theme: light # Or use dark
```

Am I not setting any paths correctly? I keep getting emailed that error from Github and I'm not sure what to change. I want to be able to run my site normally then go to `MYURL/blog` to access the home page of Chalk, but it gives me a Github 404.

**Comment by nielsenramon** [comment]
Chalk does not support default jekyll hosting on GitHub Pages, it requires the project to actually be build and deployed to a branch on github. Stylesheet not being a recognised tag is about jekyll-assets gem that is missing probably?

**Comment by nistara** [comment]
@nielsenramon , I got a similar error when I tried to deploy it as a page: 
`The tag `asset_path` on line 1 in `_posts/2016-10-15-chalk-sample-post-with-all-elements.md` is not a recognized Liquid tag.`

So Chalk can be deployed as a jekyll site hosted off github (e.g. username.github.io), but not as a page (username.github.io/chalk). Did I understand correct? Thank you!

**Comment by huyanhh** [comment]
![screen shot 2017-02-22 at 12 14 30](https://cloud.githubusercontent.com/assets/15709918/23230370/86fdbc12-f8f8-11e6-9c3a-e86c7b0f438d.png)

@nielsenramon All of the jekyll-assets gems have been installed, is this what you're talking about?

**Comment by nielsenramon** [comment]
@nistara You can but you need to put the source files on another branch: for example: `website`.
Deploy your changes to that branch and run `bin/deploy` then you can use a github.io page.

@huyanhh where did you get that error? Via mail from github?

**Comment by huyanhh** [comment]
@nielsenramon I found out what the error was. I was trying to push it manually to a gh-pages branch, but it worked once I used bin/deploy on a separate repository.
