### ISSUE TITLE
Pagination not show with high probability 

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [nielsenramon/chalk#63]
Hi there, sorry to interrupt you. I really love chalk, a charming theme. However, I met a problem when using it and hope someone could help me. 

I just copy your example articles several times to test pagination. I refresh the page and test a lot of times. I find there is **large probability** that the pagination foot does not show. For example:

This is correct pagination:
<img width="664" alt="screen shot 2017-03-03 at 11 04 27" src="https://cloud.githubusercontent.com/assets/9215584/23560915/b22c758a-0001-11e7-9566-7c9921a9aff7.png">
This is the failing pagination:

<img width="660" alt="screen shot 2017-03-03 at 11 04 17" src="https://cloud.githubusercontent.com/assets/9215584/23560958/dfd73f06-0001-11e7-8709-ff4469af297d.png">
I would really appreciate it if someone could help me to stable the pagination. Thanks in advance!

**Comment by migueldemoura** [comment]
Does that happen with chalk:master?

**Comment by Xiaoming-Zhao** [comment]
@migueldemoura  Hi, Miguel de Moura, I think so. Actually, I use VPS instead of GitHub pages. So I only have master branch.

**Comment by nielsenramon** [comment]
@Xiaoming-Zhao It's actually working perfectly for me. Any console/terminal errors? What browser?

**Comment by migueldemoura** [comment]
@Xiaoming-Zhao, if you have it online, please give us a link to help troubleshooting.

**Comment by Xiaoming-Zhao** [comment]
@nielsenramon Hi, sorry for the delay. The following is the console, I think everything works fine.

<img width="1098" alt="screen shot 2017-03-04 at 23 33 49" src="https://cloud.githubusercontent.com/assets/9215584/23584844/20ef82fa-0133-11e7-9009-dfd42556cc12.png">

**Comment by nielsenramon** [comment]
Hmm nothing I can do with that @Xiaoming-Zhao got any console errors in browser?
How many posts do you have and on how did you configure your `_config.yml` and more specifically the `paginate` variable?

**Comment by nielsenramon** [comment]
Closed because no reply, and unable to replicate issue.

**Comment by Xiaoming-Zhao** [comment]
@nielsenramon Hi there, sorry for so late reply. I think my problem is the same as #67. 

Actually, when I see this problem, I need to reload the page several times before it returns to normal, which is the same method as the user used in #67.

**Comment by nielsenramon** [comment]
@Xiaoming-Zhao Alright, I will have a look at scrollreveal then :-)

**Comment by migueldemoura** [comment]
@nielsenramon, I'm having this issue as well. The library is really buggy

**Comment by nielsenramon** [comment]
@migueldemoura Thinking about using https://github.com/michalsnik/aos any experience with that anyone?

**Comment by migueldemoura** [comment]
Did this happen before turbolinks? Hard to believe such popular lib would be buggy on its most basic use-case. AOS seems nice, maybe it'll solve the issue :roll_eyes:

**Comment by nielsenramon** [comment]
@migueldemoura We could test this with the old setup (jQuery)? I also saw that scrollreveal is going commercial so it won't be free anymore.

**Comment by migueldemoura** [comment]
I'm testing right now. By the way, where did you see that "scrollreveal is going commercial"?

**Comment by nielsenramon** [comment]
@migueldemoura Check their readme in the development branch: https://github.com/jlmakes/scrollreveal/tree/development
