### ISSUE TITLE
Post's picture thumbnail is showing another post's picture

### ISSUE THREAD

**Issue by joshuabezaleel** [nielsenramon/chalk#65]
Hi Nielsen,
First of all I would like to say thank you for the awesome theme! In fact I am using it right now for my site [here](http://joshuabezaleel.com).

I encountered a problem today. I try to share my [post](http://joshuabezaleel.com/posts/a-quick-survey-on-fomo) to Facebook and I already included a picture at the top of the post using Unsplash API but the picture that shown at the Facebook's post thumbnail is the one at the "introducing chalk" post, the default post at your theme.

Any solution for my problem? Thank you very much!
![facebook-fomo-thumbnail](https://cloud.githubusercontent.com/assets/7043511/23601447/0c2a615e-027e-11e7-95e6-db5791ae7677.JPG)
![joshuabezaleel-site-picture](https://cloud.githubusercontent.com/assets/7043511/23601459/1d6a8bba-027e-11e7-8504-93baa72e4889.JPG)

**Comment by nielsenramon** [comment]
@joshuabezaleel Did you fill in the `og_image` tag in the post header with your own? Note og-images need correct sizes!

**Comment by joshuabezaleel** [comment]
Am I unable to put an external link for the og_ image? 
Let's say `og_image: "https://source.unsplash.com/Q7wDdmgCBFg/1600x900"`

**Comment by nielsenramon** [comment]
@joshuabezaleel Not at the moment, you need to include it in your project. I'll re-open the issue and see if I find the time to support that.

**Comment by migueldemoura** [comment]
This is the issue:
`<meta property="og:image" content="{{ site.url }}{% if page.og_image %}{{ page.og_image | asset_path }}{% else %}{% asset_path og-image.jpg %}{% endif %}">`

I'll submit a PR.
