### ISSUE TITLE
How can I change the width of code block?

### ISSUE THREAD

**Issue by AurevoirXavier** [nielsenramon/chalk#69]
When I place a code block in post.

It look like this:

![image](https://cloud.githubusercontent.com/assets/16152305/23829190/aabc35c6-0725-11e7-8013-47af13f9d83b.png)

I don't want to see this scroll bar.

**Comment by nielsenramon** [comment]
@AurevoirXavier The scrollbar is there to show overflowing code. You could make Chalk grid bigger in the _variables.scss file.
