### ISSUE TITLE
Unkown tag 'asset_path' when trying to deploy locally.

### ISSUE THREAD

**Issue by TheGrandmother** [nielsenramon/chalk#70]
I keep getting the following error when i try to deploy jekyll locally.

```
+grandmother:thegrandmother.github.com<master>$ bundle exec jekyll serve
Configuration file: /home/grandmother/git/thegrandmother.github.com/_config.yml
Configuration file: /home/grandmother/git/thegrandmother.github.com/_config.yml
            Source: /home/grandmother/git/thegrandmother.github.com
       Destination: /home/grandmother/git/thegrandmother.github.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 13): Unknown tag 'asset_path' in /home/grandmother/git/thegrandmother.github.com/_includes/head.html, included in /_layouts/post.html
jekyll 3.4.1 | Error:  Liquid syntax error (line 13): Unknown tag 'asset_path'
```

I have been fiddling around with this a lot and I haven't been able to solve it and google doesn't help either.

I have managed to get it up and running on github using the Rakefile provided by http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html

I would really like to be able to deploy locally so that I can write posts and see them locally and not post half finished content to the live page.

Epic theme otherwise :)

**Comment by gradywoodruff** [comment]
I'm having a similar problem, on my github page settings i have an error that says 

> our site is having problems building: The tag asset_path on line 1 in _includes/image.html, is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/

.

**Comment by TheGrandmother** [comment]
I can also say that this problem has appeared on two machines neither of which has undergone any major fiddling around with `gem` or Jekyll.

**Comment by nielsenramon** [comment]
@TheGrandmother @gradywoodruff Looks like your jekyll-assets gem is not setup properly. Note that you cannot host Chalk from your master branch, you HAVE to use the bin/deploy command (make sure to commit + push changes first). In the settings you can set the host branch to gh-pages as that will be the one Chalk pushes to.

This is all documented btw ;-)

**Comment by TheGrandmother** [comment]
I'm almost 100% certain that i have tried that but ill give it another attempt :p

I realized that there were some inconsitencies in my hack to make the deploy script work for another branch. But I'll see if i can get it working

**Comment by TheGrandmother** [comment]
@nielsenramon 
I have tried running that. But the error remains. I think the problem stemms from me having f**** things up with using bower with root privelges.
When one uses the `bin/setup` script I needed root permissions to use `npm`.
But ill try to hack around it.

**Comment by nielsenramon** [comment]
Oh yeah, sudo is the root of all evil for sure :D

**Comment by gradywoodruff** [comment]
my problem was that i was using the wrong ruby version, sorry about that

**Comment by EmilSayahi** [comment]
I'm using the correct Ruby version, and I'm getting the same issue with line 30 of _includes/head.html.  My line 30 is:
   `<link rel="apple-touch-icon" href="{% asset_path apple-touch-icon.png %}">`
No idea why I'm having this issue.

**Comment by migueldemoura** [comment]
@EmilSayahi, can you provide your OS, ruby version, installed gems and check if those were installed using root?

**Comment by EmilSayahi** [comment]
Windows 10 using Git Shell with Ruby 2.4.1, and I have the contents of my Gemfile.lock file below (this is the list of gems, right? I'm pretty new to using them. npm and everything else is something I've never really worked with before) and I'm pretty sure they were installed using root as I ran Git Shell as admin, and there were no warnings or errors when running the setup script. It builds fine on circle.ci.
`    activesupport (4.2.9)`
      `i18n (~> 0.7)`
      `minitest (~> 5.1)`
      `thread_safe (~> 0.3, >= 0.3.4)`
      `tzinfo (~> 1.1)`
    `addressable (2.5.2)`
      `public_suffix (>= 2.0.2, < 4.0)`
    `autoprefixer-rails (7.1.3)`
      `execjs`
    `colorator (1.1.0)`
    `colored (1.2)`
    `concurrent-ruby (1.0.5)`
    `ethon (0.10.1)`
     ` ffi (>= 1.3.0)`
    `execjs (2.7.0)`
    `extras (0.3.0)`
      `forwardable-extended (~> 2.5)`
    `fastimage (2.1.0)`
    `ffi (1.9.18-x64-mingw32)`
    `forwardable-extended (2.6.0)`
    `gemoji (3.0.0)`
    `html-pipeline (2.7.0)`
      `activesupport (>= 2)`
      `nokogiri (>= 1.4)`
    `html-proofer (3.7.2)`
      `activesupport (>= 4.2, < 6.0)`
      `addressable (~> 2.3)`
      `colored (~> 1.2)`
      `mercenary (~> 0.3.2)`
      `nokogiri (~> 1.7)`
      `parallel (~> 1.3)`
      `typhoeus (~> 0.7)`
      `yell (~> 2.0)`
    `i18n (0.8.6)`
    `jekyll (3.5.2)`
      `addressable (~> 2.4)`
      `colorator (~> 1.0)`
      `jekyll-sass-converter (~> 1.0)`
     ` jekyll-watch (~> 1.1)`
      `kramdown (~> 1.3)`
      `liquid (~> 4.0)`
      `mercenary (~> 0.3.3)`
      `pathutil (~> 0.9)`
      `rouge (~> 1.7)`
      `safe_yaml (~> 1.0)`
    `jekyll-assets (2.3.2)`
      `concurrent-ruby (~> 1.0)`
      `extras (~> 0.2)`
      `fastimage (~> 2.0, >= 1.8)`
      `jekyll (~> 3.1, >= 3.0)`
      `pathutil (>= 0.8)`
      `rack (~> 1.6)`
      `sprockets (~> 3.3, < 3.8)`
    `jekyll-paginate (1.1.0)`
    `jekyll-sass-converter (1.5.0)`
      `sass (~> 3.4)`
    `jekyll-sitemap (1.1.1)`
      `jekyll (~> 3.3)`
    `jekyll-watch (1.5.0)`
     ` listen (~> 3.0, < 3.1)`
    `jemoji (0.8.0)`
      `activesupport (~> 4.0)`
      `gemoji (~> 3.0)`
      `html-pipeline (~> 2.2)`
     ` jekyll (>= 3.0)`
    `kramdown (1.14.0)`
    `liquid (4.0.0)`
    `listen (3.0.8)`
      `rb-fsevent (~> 0.9, >= 0.9.4)`
      `rb-inotify (~> 0.9, >= 0.9.7)`
   ` mercenary (0.3.6)`
    `mini_magick (4.8.0)`
    `mini_portile2 (2.2.0)`
   ` minitest (5.10.3)`
    `nokogiri (1.8.0-x64-mingw32)`
      `mini_portile2 (~> 2.2.0)`
    `parallel (1.12.0)`
    `pathutil (0.14.0)`
      `forwardable-extended (~> 2.6)`
    `public_suffix (3.0.0)`
    `rack (1.6.8)`
    `rb-fsevent (0.10.2)`
    `rb-inotify (0.9.10)`
     ` ffi (>= 0.5.0, < 2)`
    `rouge (1.11.1)`
    `safe_yaml (1.0.4)`
    `sass (3.5.1)`
      `sass-listen (~> 4.0.0)`
    `sass-listen (4.0.0)`
     ` rb-fsevent (~> 0.9, >= 0.9.4)`
      `rb-inotify (~> 0.9, >= 0.9.7)`
    `sprockets (3.7.1)`
      `concurrent-ruby (~> 1.0)`
      `rack (> 1, < 3)`
    `thread_safe (0.3.6)`
    `typhoeus (0.8.0)`
      `ethon (>= 0.8.0)`
   ` tzinfo (1.2.3)`
     ` thread_safe (~> 0.1)`
   ` uglifier (3.2.0)`
    `  execjs (>= 0.3.0, < 3)`
    `yell (2.0.7)`
