### ISSUE TITLE
Fonts not being included in _site/assets

### ISSUE THREAD

**Issue by danbrakeley** [nielsenramon/chalk#74]
I've forked `nielsenramon/chalk`, and am having problems with the fonts not ending up in the resulting `_site` folder when I serve or build.

If I sync to master, run `bundle exec jekyll serve`, and I get `Failed to load resource: the server responded with a status of 404 (Not Found)` for both `ionicons.woff` and `ionicons.ttf`.

Looking in the `_site/assets` folder, I see a complete lack of any fonts:

```
$ ls _site/assets
about.jpg  apple-touch-icon.png  application.js  documentation  light.css  notfound-light.css  og-image.jpg  vendor.js
```

**Comment by nielsenramon** [comment]
@danbrakeley Any other issues? Is jekyll-assets properly installed? What version of jekyll-assets you running? Made any changes?

**Comment by renanvalentin** [comment]
I've created a PR to fix this: https://github.com/nielsenramon/chalk/pull/78

**Comment by renanvalentin** [comment]
I think it's a problem with jekyll-assets' `cache` https://github.com/jekyll/jekyll-assets/issues/371

**Comment by nielsenramon** [comment]
@danbrakeley Please test latest commit on master. Thanks @renanvalentin for the fix!
