### ISSUE TITLE
New to Jekyll, is this a Ruby Gem? How do I install this?

### ISSUE THREAD

**Issue by VictorioBerra** [nielsenramon/chalk#8]
[The Jekyll documentation](http://jekyllrb.com/docs/themes/) says to install a theme using these steps:

- To install a theme, first, add the theme to your site’s `Gemfile`
  - gem '`my-awesome-jekyll-theme`'
- Save the changes to your Gemfile
- Run the command bundle install to install the theme

Is this theme installed differently?

**Comment by nielsenramon** [comment]
@VictorioBerra Yeah this one is different. I can't include custom plugins into a jekyll theme so I made this one differently.

Please look at the README.md file to see how you can set it up :)

**Comment by VictorioBerra** [comment]
Good to know. Thank you.
