### ISSUE TITLE
Weird error in the console

### ISSUE THREAD

**Issue by EQuimper** [nielsenramon/chalk#82]
Firts thing good job with this template I loved it. My blog https://equimper.me get some weird error in the console. Got some problem with ScrollReveal not required etc. 
<img width="1552" alt="screen shot 2017-04-30 at 6 53 50 pm" src="https://cloud.githubusercontent.com/assets/15819498/25568690/6709bc86-2dd6-11e7-99dd-8df3d635eeb6.png">
<img width="1552" alt="screen shot 2017-04-30 at 6 53 42 pm" src="https://cloud.githubusercontent.com/assets/15819498/25568691/670bb34c-2dd6-11e7-9c85-57f1014f655c.png">

**Comment by nielsenramon** [comment]
@EQuimper Looks like your javascript dependencies aren't installed :-) We now use Yarn, so go ahead and pull the new version!
