### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by rollonbears234** [nielsenramon/chalk#9]
I am getting the following error

Error in _assets/stylesheets/light.scss:50 File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.
Load paths:
  /Users/bryanalcorn/Downloads/chalk-master/_assets/css
  /Users/bryanalcorn/Downloads/chalk-master/_assets/stylesheets
  /Users/bryanalcorn/Downloads/chalk-master/_assets/images
  /Users/bryanalcorn/Downloads/chalk-master/_assets/img
  /Users/bryanalcorn/Downloads/chalk-master/_assets/fonts
  /Users/bryanalcorn/Downloads/chalk-master/_assets/javascripts
  /Users/bryanalcorn/Downloads/chalk-master/_assets/js
  /Users/bryanalcorn/Downloads/chalk-master/_assets/bower
  /Users/bryanalcorn/Downloads/chalk-master/_vendor
  Liquid Exception: File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss. Load paths: /Users/bryanalcorn/Downloads/chalk-master/_assets/css /Users/bryanalcorn/Downloads/chalk-master/_assets/stylesheets /Users/bryanalcorn/Downloads/chalk-master/_assets/images /Users/bryanalcorn/Downloads/chalk-master/_assets/img /Users/bryanalcorn/Downloads/chalk-master/_assets/fonts /Users/bryanalcorn/Downloads/chalk-master/_assets/javascripts /Users/bryanalcorn/Downloads/chalk-master/_assets/js /Users/bryanalcorn/Downloads/chalk-master/_assets/bower /Users/bryanalcorn/Downloads/chalk-master/_vendor in /_layouts/post.html
jekyll 3.3.0 | Error:  File to import not found or unreadable: ../bower/fluidbox/src/css/_fluidbox.scss.

**Comment by nielsenramon** [comment]
@rollonbears234 Please run bin/setup (it looks like you did not run bower install). It's in the readme :)

**Comment by rollonbears234** [comment]
Thanks, I ran the setup, but I did not notice that bower was not installed. Will try to fix it now

Great template by the way, can't wait to get a site up and running!
