### ISSUE TITLE
About page still accessible when about_enabled is false

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#92]
Accessing /about when that page is disabled still outputs the about.html file since it isn't excluded from the build process.
A quick fix is making these changes to the `_config.yml` file:

```` yaml
.
.
about_enabled: true
#exclude: &about about.html
.
.
exclude:
  - *about
  - .travis.yml
  -  ...
.
.
````

To disable the about page one needs to set `about_enabled` to false and also uncomment the `exclude: &about about.html line`. The two lines can be merged together to be easier for the user, but you lose some intuitiveness. 

Another way to fix this is by adding custom logic to the about.html, but it ends up being less clean (though more user-friendly).

**Comment by nielsenramon** [comment]
@migueldemoura The about page should always be there as it is accessible through the footer. about_enabled is only about the icon in the top navigation :-)

**Comment by migueldemoura** [comment]
Got it :) . What do you think about changing `about_enabled` to `about_icon_enabled` then?

**Comment by nielsenramon** [comment]
@migueldemoura Perfect for me :D
