### ISSUE TITLE
Retinajs path can't be found

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#95]
The retinajs guys removed bower.json from the repo and released a new version that breaks our setup.
They [have reversed that](https://github.com/strues/retinajs/commit/98d2df11b1603ed66b454ef74d4f4f870400cbc9) but the changes haven't been pushed yet.

To address this, one needs to makes this change to `_assets/javascripts/vendor.js`:

``` javascript
//= require retinajs
```

to

``` javascript
//= require retinajs/dist/retina.js
```

**Comment by nielsenramon** [comment]
Fixed!
