### ISSUE TITLE
Can't Generate Theme Locally

### ISSUE THREAD

**Issue by misterjules** [nielsenramon/chalk#97]
I was getting this error in Terminal

`Liquid Exception: undefined method "line_number" for "":String in /_layouts/post.html
jekyll 3.5.0 | Error:  undefined method "line_number" for "":String`

I found the error in `/_includes/head.html`

it was with these two lines

`{% assign thumb_image = page.thumb_image | asset_path | absolute_url %}
  {% endif %}
{% else %}
  {% assign thumb_image = og-image.jpg | asset_path | absolute_url %}
{% endif %}`

Once I removed `|`. I could generate the theme locally for development.

I've also run into a problem when running your deploy script, but I think that's because I'm using Gitlab. I don't know anything about scripts and was wondering if there was a way, I could tailor the script so that it would push and deploy to a Gitlab repo instead of Github.

Jules

**Comment by nielsenramon** [comment]
@misterjules 

Can you confirm that you have a og-image.jpg? Or that you entered a og image in the post?

Also please use the latest version of Chalk from the master branch please.

I haven't tested the script with GitLab at all. It's on my todo list tho!

**Comment by migueldemoura** [comment]
Likely exploding due to that field not being defined. Should probably add a `is_empty` check.

**Comment by misterjules** [comment]
@nielsenramon 

I downloaded the latest version. Same thing still happens.

FYI `_assets/yarn` is missing in the latest build which is looking for those assets when served

**Comment by migueldemoura** [comment]
@misterjules, `_assets/yarn` is generated when running `./bin/setup`

**Comment by misterjules** [comment]
@migueldemoura 

Right. Forgot about that. I just added the `_assets/yarn` folder from a previous version into the latest build when running locally

**Comment by nielsenramon** [comment]
@misterjules So it's working now? :-)

**Comment by misterjules** [comment]
@nielsenramon yes. Only If I remove `|` from those 2 lines in my first post. When @migueldemoura said I should add an `is_empty` check; I don't know what that means or how to even do it. So, I just left it how I did it.

**Comment by migueldemoura** [comment]
@misterjules, can you put here the header of your post (lines between `-----`)?

**Comment by misterjules** [comment]
@migueldemoura this is the code from `_/includes/head.html`

```
{% if page.thumb_image %}
  {% if page.thumb_image contains :// %}
    {% assign thumb_image = page.thumb_image %}
  {% else %}
    {% assign thumb_image = page.thumb_image asset_path absolute_url %}
  {% endif %}
{% else %}
  {% assign thumb_image = og-image.jpg asset_path absolute_url %}
{% endif %}
<head>
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{{ site.name }} | {{ page.title }}</title>
  <meta name="description" content="{{ page.description }}">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="{{ page.title | escape }}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ page.url | absolute_url }}">
  <meta property="og:description" content="{{ page.description }}">
  <meta property="og:site_name" content="{{ site.name }}">
  <meta property="og:image" content="{{ thumb_image }}">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:url" content="{{ page.url | absolute_url }}">
  <meta name="twitter:title" content="{{ page.title | escape }}">
  <meta name="twitter:description" content="{{ page.description }}">
  <meta name="twitter:image" content="{{ thumb_image }}">

  <link rel="apple-touch-icon" href="{% asset_path apple-touch-icon.png %}">
  <link href="{{ feed.xml | absolute_url }}" type="application/rss+xml" rel="alternate" title="{{ site.name }} Last 10 blog posts" />

  {% if site.local_fonts %}
    {% include stylesheet.html path="fonts" %}
  {% endif %}

  {% if site.blog_theme == "light" %}
    {% include stylesheet.html path="light" %}
  {% else %}
    {% include stylesheet.html path="dark" %}
  {% endif %}
  {% seo %}
</head>
```

**Comment by migueldemoura** [comment]
@misterjules, I meant the content of `_/posts/your-post.md`. Or did this error occur without touching any file?

**Comment by misterjules** [comment]
The only things I touched were `_config.yml` and a few of the stylesheets. I left everything else alone.

**Comment by migueldemoura** [comment]
Can you upload your project somewhere so I can reproduce it?

**Comment by misterjules** [comment]
https://gitlab.com/mrjules/chalked5

**Comment by migueldemoura** [comment]
@misterjules, cloned, ran `./bin/setup` and `bundle exec jekyll serve` and didn't get that error. Can you provide steps to get that error?

**Comment by misterjules** [comment]
replace this code 

`{% if page.thumb_image %}
  {% if page.thumb_image contains :// %}
    {% assign thumb_image = page.thumb_image %}
  {% else %}
    {% assign thumb_image = page.thumb_image asset_path absolute_url %}
  {% endif %}
{% else %}
  {% assign thumb_image = og-image.jpg asset_path absolute_url %}
{% endif %}`

in `_includes/head.html` with

`{% if page.thumb_image %}
  {% if page.thumb_image contains '://' %}
    {% assign thumb_image = page.thumb_image %}
  {% else %}
    {% assign thumb_image = page.thumb_image | asset_path | absolute_url %}
  {% endif %}
{% else %}
  {% assign thumb_image = 'og-image.jpg' | asset_path | absolute_url %}
{% endif %}`

**Comment by migueldemoura** [comment]
I got this error: `Could not find the asset 'og-image.jpg'`, caused by the removal of `_assets/og-image.jpg`. If you want a default thumb_image, replace that file with the one you like. Otherwise, replace those lines with:
```
{% if page.thumb_image contains '://' %}
    {% assign thumb_image = page.thumb_image %}
  {% else %}
    {% assign thumb_image = page.thumb_image | asset_path | absolute_url %}
{% endif %}
```

**Comment by misterjules** [comment]
Thanks @migueldemoura . I have another issue if I can add it here or open up another issue? Posts seem to be broken on Gitlab Pages. Everything looks fine on https://mrjules.gitlab.io/chalked5 until you click on a link. I added `baseurl: /chalked5` to the `_config.yml` . Should I be adding `{{ site.baseurl }}` next to liquid tags with `{{ post.url }}` ?

**Comment by migueldemoura** [comment]
Open a new issue, I'm guessing that @nielsenramon didn't take that use-case into account.

**Comment by misterjules** [comment]
ok, will do.

**Comment by migueldemoura** [comment]
@nielsenramon, might be a good idea to add a check for `og-image.jpg`
