### ISSUE TITLE
Posts/Pages Broken on Gitlab Pages

### ISSUE THREAD

**Issue by misterjules** [nielsenramon/chalk#98]
Posts and (1) page seem to be broken on Gitlab Pages. Everything looks fine on https://mrjules.gitlab.io/chalked5 until you click on a link. I added `baseurl: /chalked5` to the `_config.yml` . Should I be adding `{{ site.baseurl }}` next to liquid tags with `{{ post.url }}` ?

**UPDATE**

Ran htmlproofer and it found 17 errors; excluding files from `/_site/`

  *  internally linking to /about, which does not exist (line 165)
`     <a href="/about" title="About me">Nielsen Ramon</a>`
  *  internally linking to /posts/chalk-sample-post-with-all-elements, which does not exist (line 129)
```
     <a href="/posts/chalk-sample-post-with-all-elements" title="Chalk sample post with all elements">
        <h5>
          Chalk sample post with all elements
          <span class="icon icon-arrow-right"></span>
        </h5>
      </a>
```
  *  internally linking to /posts/configuring-chalk, which does not exist (line 99)
```
     <a href="/posts/configuring-chalk" title="How to configure Chalk">
        <h5>
          How to configure Chalk
          <span class="icon icon-arrow-right"></span>
        </h5>
      </a>
```
  *  internally linking to /posts/introducing-chalk, which does not exist (line 69)
```
     <a href="/posts/introducing-chalk" title="Introducing chalk">
        <h5>
          Introducing chalk
          <span class="icon icon-arrow-right"></span>
        </h5>
      </a>
```

**Comment by migueldemoura** [comment]
I believe your observation is correct - maybe submit a PR? As for the htmlproofer issues, they are expected and can be safely ignored - associations are generated afterwards afaik.

**Comment by misterjules** [comment]
I think it has something to do with this line in `index.html`

    <a href="{{ post.url | relative_url }}" title="{{ post.title }}"></a>

when I add `{{ post }}` in this line

`<a href="{{ post.url | relative_url }}{{ post }}" title="{{ post.title }}">`

the posts *at least* show on the `index.html`, even though it makes the site look broken. When `{{ post }}` is removed the main page looks normal, but when clicking on posts they lead to a 404...

I've also tried replacing the line above with `<a href="{{ post.url | absolute_url }}">{{ post.title }}</a>` and setting in _config.yml the property: baseurl="" – or `<a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>`

**Comment by misterjules** [comment]
Solved my issue. The problem was with my permalink in `_config.yml`.

I had changed it from its original `permalink: posts/:slug` to `permalink: /:year/:month/:slug`. If someone didn't point out the `.html` in the help I received on Stackoverflow, I would have never thought to check my `permalink` in `_config.yml`. All I did was replace `:slug` with `:title.html` and the blog posts open.
