### ISSUE TITLE
Enhancement: Load JS asynchronously for PageSpeed improvements

### ISSUE THREAD

**Issue by madcatsu** [nielsenramon/chalk#99]
See Filament Group's loadCSS library for further reference:

- [loadCSS repo](https://github.com/filamentgroup/loadCSS)
- [NPM module](https://www.npmjs.com/package/fg-loadcss) which could be included with Yarn

Current Google PageSpeed insights recommends loading JS asynchronously to stop page blocking while loading script resources. This could be achieved with the `asynch` option but browser support is limited where loadCSS provides a wider variety of support.

**Comment by migueldemoura** [comment]
Some js can't be easily loaded in an async fashion, as some of it has dependencies, like jQuery. How do you propose doing it? As the js is all appended to the end of the html, the `defer` option also doesn't make sense.

Finally, can you explain a little further how loadCSS would help? I skimmed through the README and didn't understand how it would benefit Chalk. Afaik, preloading isn't useful as the css is the same on every page.

Thanks!

**Comment by madcatsu** [comment]
@migueldemoura would depend on how much of the site skeleton is loaded but perhaps concatenating all the JS resources with Uglify through the jekyll-asset pipeline might assist. 

I'm not sure if the asset pipeline will allow ordering of how all the JS is combined though, the other option would be to concatenate the JS before passing it through Uglify. I think that gets messy though as Gulp or Grunt tasks might be needed for that type of workflow. 

I haven't dug deep enough yet to understand how much of the site relies on JS to provide the bare essentials for the site to load a usable HTML skeleton before any of the other UI elements are imported.

**Comment by migueldemoura** [comment]
The theme works without js, as it is only used to enhance the experience. If you're loading the scripts, the first thing needs to be jQuery, then scroll appear and then everything else.

**Comment by madcatsu** [comment]
Closed. Will investigate using WebPack to achieve this.
